### PR TITLE
Allow setting shortcut to open popup

### LINKED ISSUE #70: Please support keyboard shortcuts
After I tried tons of extension managers, there is no doubt that this is the best one. 
It would be better if you could add the keyboard shortcuts!

### PR DESCRIPTION
**Pull request by fregante**
Closes #70 

cc @Alphabet1226

### CODE REVIEW

**Comment by fregante** [comment]
Screen Shot

**Comment by Alphabet1226** [comment]
I updated to the latest version (0805) and set the shortcut keys, but it doesn't seem to work. I tested it in the latest stable version of Chrome and edge respectively, and both results are not working.

**Comment by fregante** [comment]
Thanks for the report! It seems that Google renamed the option so even if it showed the UI it didn't work 🤦‍♂️ 

https://groups.google.com/a/chromium.org/g/chromium-extensions/c/eKcVRVOQ4GU

**Comment by Alphabet1226** [comment]
🤦‍♂️All right

**Comment by hankxdev** [comment]
Maybe switch to manifest v2 for now? Didn't see any improvement on v3. Only
bugs🙃

**Comment by fregante** [comment]
Fair enough. I will publish 21.8.7 tomorrow. In reality none of the recent changes were necessary, it's just that to make the shortcut work you have to disable and then re-enable the extension with v3.

**Pull request merged**
