### PR TITLE
Fix undo not working 

### LINKED ISSUE #94: UNDO/REDO is not working
Not sure when it started (not using this feature very often...)

### PR DESCRIPTION
**Pull request by hankxdev**
By binding the scope, fixed #94 .

also including a little format change made by prettier

### CODE REVIEW

**Comment by fregante** [comment]
Wow this means it hasn't worked for a while. Let me try something

**Review by fregante — APPROVED** [review]
It's fine for now

**Comment by fregante** [comment]
Can you rename the `master` branch to `main` after merge?

**Comment by hankxdev** [comment]
yeah, renamed

**Pull request merged**
