### PR TITLE
fix webstore link in the edge browser

### LINKED ISSUE #76: 无法打开edge商店链接
报告一个小bug，鼠标右键点击项目，再点那个地球图标时，无法打开edge扩展商店，在chrome上是正常的。

### PR DESCRIPTION
**Pull request by hankxdev**
change the logic to generate the webstore URL so that it works in Edge browser.

fixed #76

### CODE REVIEW

**Comment by fregante** [comment]
I wish you didn't change the whitespace… there are a lot of issues. Please wait for a review before merging 😅

**Comment by fregante** [comment]
There's a bug I'd like to fix before the next version

**Comment by hankxdev** [comment]
@fregante I did not, it's just the xo or eslint seems not to work well for svelte, the `fix` or `lint` only apply a wrong check for new lines.

**Comment by fregante** [comment]
Yeah, it's best to run those updates/lint changes in their own PR

**Comment by hankxdev** [comment]
> Yeah, it's best to run those updates/lint changes in their own PR

yeah, agree.

**Comment by fregante** [comment]
I'm making some changes now, I will send a PR soon

**Pull request merged**
